services:
  envoy:
    image: envoyproxy/envoy:v1.33-latest
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--service-cluster", "model-api-platform"]
    ports:
      - "8081:8081"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
